# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-05 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_graphmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_netjsonconfig.Config', unique=True),
        ),
    ]
