# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-05 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_auto_20170305_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='config',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='django_netjsonconfig.Config'),
        ),
    ]
